chore: enhance `aigd` script with Fabric integration and error checks
- Add usage instructions for `aigd` script
- Integrate Fabric for summarizing git changes
- Implement error handling for Fabric installation
- Modify script to handle optional file argument
- Add check for empty git diff output
- Update script to exit gracefully if no changes

diff --git a/scripts/aigd b/scripts/aigd
--- a/scripts/aigd
+++ b/scripts/aigd
@@ -1,13 +1,32 @@
 #!/usr/bin/env bash
 
-# This scripts provides a human-language summary and explanation of your code changes based on your `git diff` results.
+# Summarize git changes with Fabric
+# Usage: aigd [file]
+
+set -e
 
 file=$1
 
-if ! command -v fabric  &> /dev/null/; then
-	echo "Error: Fabric is not installed on your device. Please install and try again. See ./scripts/readme.md to install"
-	
-	exit 1
+FABRIC_BIN="$HOME/.local/bin/fabric"
+
+if [[ ! -x "$FABRIC_BIN" ]]; then
+  echo "Error: fabric hasn't been properly installed"
+  echo "👉 Please review ./scripts/readme.md to install"
+  exit 1
 fi
 
-git diff "$file" | fabric -p summarize_git_diff
+# Read `git diff` output
+if [[ -n "$file" ]]; then
+	diff_output=$(git diff "$file")
+else
+	diff_output=$(git diff) # Reads `git diff` for entire repo
+fi
+
+# Exit if there are no changes
+if [[ -z "$diff_output" ]]; then
+	echo "🌱 No changes to summarise..."
+	exit 0
+fi
+
+echo "$diff_output" | fabric -p summarize_git_diff
+
